meta:
  device: 'cuda'
  seed: [1,2,3,4,5]
  out_root_dir: 'out/'
rag:
  model:
    cfg_path: ['configs/model/llama3.1_70b_together.yaml'] 
    skip: false
  embedder_name: 'openai'
  real_retrieval: true
  n_shots: 3 
  defended: [false, true]
attacker:
  model:
    cfg_path: 'configs/model/llama3.1_8b.yaml' 
    skip: false
  algos:
    - "watermark" 
  give_explicit_ids: true
  watermark:
      scheme: 'kgw'
      generation:
        - seeding_scheme: ['ff-position_prf-2-False-1548585']
          gamma: 0.25
          delta: 3.5
      detection:
        normalizers: []
        ignore_repeated_ngrams: true 
        z_threshold: 4.0 
eval:
  setting1: true 
  setting2: true 