meta:
  device: 'cuda'
  seed: [1]
  out_root_dir: 'out/'
rag:
  model:
    cfg_path: ['configs/model/gpt3.5.yaml'] 
    skip: false
  embedder_name: 'sentence-transformers/all-MiniLM-L6-v2'
  n_shots: 3 
  defended: [true]
attacker:
  model:
    cfg_path: 'configs/model/llama3.1_8b.yaml' 
    skip: false
  algos:
    - "facts"
  give_explicit_ids: true
  watermark:
      scheme: 'kgw'
      generation:
        - seeding_scheme: ['ff-position_prf-2-False-1548585']
          gamma: 0.25
          delta: 3.5
      detection:
        normalizers: []
        ignore_repeated_ngrams: true 
        z_threshold: 4.0 
eval:
  setting1: false 
  setting2: true 